//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitizenDataAccessLayer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address_Details()
        {
            this.Citizens = new HashSet<Citizen>();
        }
    
        public string Address_Line1 { get; set; }
        public string Address_Line2 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<int> Pin_Code { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public int Address_Details_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citizen> Citizens { get; set; }
    }
}
