//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitizenDataAccessLayer.Entity
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class Citizen
    {
        public string Name { get; set; }
        public string Father_Name { get; set; }
        public string Occupation { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public int Citizens_ID { get; set; }
        public Nullable<int> Address_Details_ID { get; set; }

        public virtual Address_Details Address_Details { get; set; }
    }
}
